### PR TITLE
New buttons template

### PR DESCRIPTION
**Pull request by Reshex**
Added new buttons scss and logic
I have added button examples in the HomeMain component in order for you to see how I used it and how it looks

### CODE REVIEW

**Review by talyaron — CHANGES_REQUESTED** [review]
Hi Bar, Nice job. , Please check with Masha that the buttons look as she asked. 
and also, remove the example buttons from home.

**Comment by Reshex** [comment]
> Hi Bar, Nice job. , Please check with Masha that the buttons look as she asked. and also, remove the example buttons from home.

I have consulted with Masha, and she approved the changes

**Review by talyaron — CHANGES_REQUESTED** [review]
Hi Bar please look at this request:
https://somup.com/cZiXiYEsVU

**Comment by talyaron** [comment]
Approved and merged

**Comment by talyaron** [comment]
Thanks

**Pull request closed without merging**
