### PR TITLE
Description resize

### PR DESCRIPTION
**Pull request by LeeDek**
window height fit content.

### CODE REVIEW

**Review by talyaron — APPROVED** [review]
Cool, thanks

**Comment by talyaron** [comment]
Good morning Lee, Your PR has failed on Lint. Can you please run ```npm run lint``` to check where it falls, and fix it?

**Comment by LeeDek** [comment]
> Good morning Lee, Your PR has failed on Lint. Can you please run `npm run lint` to check where it falls, and fix it?



> Good morning Lee, Your PR has failed on Lint. Can you please run `npm run lint` to check where it falls, and fix it?

Color property fixed

**Comment by talyaron** [comment]
Closed in manually. Thanks

**Pull request closed without merging**
